# ------------------ JUPYTER BOOK CONFIG ------------------
title: "SSP Data Forums"
author: "NOAA Weather Program Office"
copyright: "© NOAA WPO"
logo: "_static/Lockup-Horizontal.png"

# Build & execution
execute:
  execute_notebooks: off   # auto | force | cache | off
  timeout: 120

# Repository metadata (enables Binder/Edit buttons)
repository:
  url: https://github.com/jmote-noaa/Data-Forums  # <-- update if different
  branch: main
  path_to_book: ""   # repo root; set to subfolder if your book lives elsewhere

# Launch buttons (Binder + Thebe)
launch_buttons:
  binderhub_url: https://mybinder.org
  notebook_interface: jupyterlab  # or "classic"
  thebe: true

# Optional explicit Thebe config (usually inferred from 'repository' above)
thebe_config:
  repository_url: https://github.com/jmote-noaa/Data-Forums
  repository_branch: main

# HTML / Theme
html:
  favicon: "_static/favicon.ico"
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: true
  baseurl: ""  # leave blank for GitHub Pages at user/org root
  extra_navbar: ""
  extra_footer: ""
  extra_css:
    - "_static/custom.css"
  theme:
    name: sphinx_book_theme
    options:
      repository_url: https://github.com/jmote-noaa/Data-Forums
      repository_branch: main
      path_to_docs: ""     # keep empty if book is at repo root
      home_page_in_navbar: true
      use_repository_button: true
      use_edit_page_button: true
      use_download_button: true
      show_navbar_depth: 1

# Parsing & content
only_build_toc_files: true
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution

# Sphinx extras
sphinx:
  extra_extensions:
    - sphinx_copybutton
  config:
    html_show_copyright: false
    myst_heading_anchors: 3
