name: data-forums
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - jupyter-book
  - numpy
  - pandas
  - requests
  - tqdm
  - matplotlib
  - seaborn
  # --- Geo stack (for GeoPandas / Shapely) ---
  - geopandas
  - shapely
  - pyproj
  - rtree
  - fiona
